import './globals.css'
import {Inter} from 'next/font/google'
import style from './Layout.module.scss'
import Modal from "@/components/modal/Modal";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Provider from "@/components/provider/Provider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Testovoe',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Provider>
            <div className={style.wrapper}>
                <Modal/>
                <Header/>
                {children}
                <Footer/>
            </div>
        </Provider>
        </body>
        </html>
    )
}
